import type { EscalationMatrix, ImportantDocument, InwardRegister, LegalNotice } from "./types"

export const mockDocuments: ImportantDocument[] = [
  {
    id: "DOC-001",
    department: "HR",
    documentType: "CLRA",
    periodFrom: "2023-01-15",
    periodTo: "2025-01-14",
    expiryDate: "2025-01-14",
    inwardNumber: "IN-2023-001",
    inwardDate: "2023-01-15",
    autoRenewalAlert: true,
    responsiblePerson: "John Smith",
    escalationL1: "Manager",
    escalationL2: "Director",
    escalationL3: "Executive",
    status: "Active",
    createdAt: "2023-01-15",
    updatedAt: "2024-12-20",
  },
  {
    id: "DOC-002",
    department: "OPERATIONS",
    documentType: "ISO_CERT",
    periodFrom: "2022-06-10",
    periodTo: "2025-06-09",
    expiryDate: "2025-06-09",
    inwardNumber: "IN-2022-045",
    inwardDate: "2022-06-10",
    autoRenewalAlert: false,
    responsiblePerson: "Sarah Johnson",
    escalationL1: "QA Lead",
    escalationL2: "Operations Head",
    escalationL3: "CEO",
    status: "Active",
    createdAt: "2022-06-10",
    updatedAt: "2024-11-15",
  },
  {
    id: "DOC-003",
    department: "ADMIN",
    documentType: "SHOP_ACT",
    periodFrom: "2020-03-20",
    periodTo: "2025-03-19",
    expiryDate: "2025-03-19",
    inwardNumber: "IN-2020-012",
    inwardDate: "2020-03-20",
    autoRenewalAlert: true,
    responsiblePerson: "Michael Brown",
    escalationL1: "Compliance Officer",
    escalationL2: "Legal Head",
    escalationL3: "COO",
    status: "Expired",
    createdAt: "2020-03-20",
    updatedAt: "2025-01-05",
  },
  {
    id: "DOC-004",
    department: "OPERATIONS",
    documentType: "ELECTRICAL",
    periodFrom: "2024-02-01",
    periodTo: "2025-01-31",
    expiryDate: "2025-01-31",
    inwardNumber: "IN-2024-078",
    inwardDate: "2024-02-01",
    autoRenewalAlert: true,
    responsiblePerson: "Emily Davis",
    escalationL1: "Facility Manager",
    escalationL2: "Operations Head",
    escalationL3: "CFO",
    status: "Active",
    createdAt: "2024-02-01",
    updatedAt: "2024-12-15",
  },
]

export const mockRegister :InwardRegister[]=[
  {
    department:"HR",
    receivedDate:"2026-01-10",
    receivingPerson:"pratik",
    forwardToPerson:"ops",
    documentType:"LETTER",
    physicalFileNo:"21",
    id:"INR-001",
    createdAt:"2024-11-25",
    updatedAt:"2024-10-26"
    
  }
]

export const mockEscalationMatrix: EscalationMatrix[] = [
  {
    id: "ESC-001",
    department: "HR",
    l1: { name: "Priya Sharma", email: "priya.sharma@company.com" },
    l2: { name: "Rohit Mehta", email: "rohit.mehta@company.com" },
    l3: { name: "Anita Kapoor", email: "anita.kapoor@company.com" },
    l4: { name: "Vikram Singh", email: "vikram.singh@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-002",
    department: "OPERATIONS",
    l1: { name: "Arjun Rao", email: "arjun.rao@company.com" },
    l2: { name: "Neha Iyer", email: "neha.iyer@company.com" },
    l3: { name: "Sandeep Nair", email: "sandeep.nair@company.com" },
    l4: { name: "Karan Malhotra", email: "karan.malhotra@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-003",
    department: "ADMIN",
    l1: { name: "Meera Joshi", email: "meera.joshi@company.com" },
    l2: { name: "Amit Verma", email: "amit.verma@company.com" },
    l3: { name: "Pooja Sethi", email: "pooja.sethi@company.com" },
    l4: { name: "Rakesh Gupta", email: "rakesh.gupta@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-004",
    department: "ACCOUNTS",
    l1: { name: "Nitin Shah", email: "nitin.shah@company.com" },
    l2: { name: "Komal Patel", email: "komal.patel@company.com" },
    l3: { name: "Deepak Arora", email: "deepak.arora@company.com" },
    l4: { name: "Ritu Bansal", email: "ritu.bansal@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-005",
    department: "BILLING",
    l1: { name: "Sonal Jain", email: "sonal.jain@company.com" },
    l2: { name: "Harsh Kulkarni", email: "harsh.kulkarni@company.com" },
    l3: { name: "Devika Roy", email: "devika.roy@company.com" },
    l4: { name: "Manish Tandon", email: "manish.tandon@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-006",
    department: "LEGAL",
    l1: { name: "Radhika Sen", email: "radhika.sen@company.com" },
    l2: { name: "Alok Deshmukh", email: "alok.deshmukh@company.com" },
    l3: { name: "Shweta Chopra", email: "shweta.chopra@company.com" },
    l4: { name: "Gaurav Khanna", email: "gaurav.khanna@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-007",
    department: "FINANCE",
    l1: { name: "Pankaj Mittal", email: "pankaj.mittal@company.com" },
    l2: { name: "Seema Nanda", email: "seema.nanda@company.com" },
    l3: { name: "Naveen Suri", email: "naveen.suri@company.com" },
    l4: { name: "Tina Ahuja", email: "tina.ahuja@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-008",
    department: "QUALITY",
    l1: { name: "Farah Ali", email: "farah.ali@company.com" },
    l2: { name: "Keshav Bhatia", email: "keshav.bhatia@company.com" },
    l3: { name: "Ishita Dey", email: "ishita.dey@company.com" },
    l4: { name: "Rohan Chawla", email: "rohan.chawla@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "ESC-009",
    department: "ENVIRONMENTAL",
    l1: { name: "Leena Bose", email: "leena.bose@company.com" },
    l2: { name: "Vivek Saran", email: "vivek.saran@company.com" },
    l3: { name: "Asha Menon", email: "asha.menon@company.com" },
    l4: { name: "Pranav Oberoi", email: "pranav.oberoi@company.com" },
    createdAt: "2026-01-10T09:00:00.000Z",
    updatedAt: "2026-01-10T09:00:00.000Z",
  },
]

export const mockLegalNotices: LegalNotice[] = [
  {
    id: "LN-001",
    relatedDocumentId: "DOC-001",
    department: "HR",
    subject: "Contract Labour Compliance Review",
    inwardNumber: "IN-LN-2024-001",
    inwardDate: "2024-11-20",
    replies: [
      {
        text: "Initial assessment completed. All documentation in order.",
        type: "Own",
        responsiblePerson: "John Smith",
        createdAt: "2024-11-25",
      },
    ],
    period: "30 days",
    amount: 5000,
    remarks: "Routine compliance check",
    stage: "Open",
    finalStatus: "Pending",
    alertDays: 5,
    escalationL1: "Manager",
    escalationL2: "Director",
    createdAt: "2024-11-20",
    updatedAt: "2024-12-20",
  },
  {
    id: "LN-002",
    department: "LEGAL",
    subject: "Tax Notice - FY 2023-24",
    inwardNumber: "IN-LN-2024-002",
    inwardDate: "2024-10-15",
    replies: [
      {
        text: "Engaged external advocate for review.",
        type: "Advocate",
        responsiblePerson: "Advocate ABC",
        createdAt: "2024-10-20",
      },
      {
        text: "Initial response filed.",
        type: "Own",
        responsiblePerson: "Legal Team",
        createdAt: "2024-11-10",
      },
    ],
    period: "60 days",
    amount: 25000,
    remarks: "Tax demand notice - under review",
    stage: "Open",
    finalStatus: "In Progress",
    alertDays: 15,
    escalationL1: "Legal Head",
    escalationL2: "CFO",
    createdAt: "2024-10-15",
    updatedAt: "2024-12-15",
  },
  {
    id: "LN-003",
    department: "OPERATIONS",
    relatedDocumentId: "DOC-003",
    subject: "Shop Act Violation Notice",
    inwardNumber: "IN-LN-2024-003",
    inwardDate: "2024-09-01",
    replies: [
      {
        text: "Corrective measures implemented.",
        type: "Own",
        responsiblePerson: "Michael Brown",
        createdAt: "2024-09-10",
      },
      {
        text: "Consultant reviewed and approved.",
        type: "Consultant",
        responsiblePerson: "Safety Consultant",
        createdAt: "2024-09-20",
      },
    ],
    period: "45 days",
    amount: 3000,
    remarks: "Minor violations - resolved",
    stage: "Closed",
    finalStatus: "Resolved",
    alertDays: 0,
    escalationL1: "Operations Head",
    escalationL2: "COO",
    createdAt: "2024-09-01",
    updatedAt: "2024-10-15",
  },
  {
    id: "LN-004",
    department: "FINANCE",
    subject: "Labor Law Compliance - Minimum Wage Adjustment",
    inwardNumber: "IN-LN-2024-004",
    inwardDate: "2024-12-01",
    replies: [
      {
        text: "Reviewing updated wage structure for compliance.",
        type: "Own",
        responsiblePerson: "HR Manager",
        createdAt: "2024-12-05",
      },
    ],
    period: "30 days",
    amount: 8500,
    remarks: "Annual wage adjustment notification",
    stage: "Open",
    finalStatus: "Pending",
    alertDays: 20,
    escalationL1: "Finance Head",
    escalationL2: "COO",
    createdAt: "2024-12-01",
    updatedAt: "2025-01-08",
  },
  {
    id: "LN-005",
    department: "QUALITY",
    relatedDocumentId: "DOC-002",
    subject: "ISO Certification - Audit Finding Review",
    inwardNumber: "IN-LN-2024-005",
    inwardDate: "2024-11-10",
    replies: [
      {
        text: "Non-conformity identified during audit.",
        type: "Audit Body",
        responsiblePerson: "Audit Team XYZ",
        createdAt: "2024-11-12",
      },
      {
        text: "Corrective action plan submitted.",
        type: "Own",
        responsiblePerson: "Sarah Johnson",
        createdAt: "2024-11-28",
      },
      {
        text: "Follow-up audit scheduled for February 2025.",
        type: "Audit Body",
        responsiblePerson: "Audit Team XYZ",
        createdAt: "2025-01-05",
      },
    ],
    period: "90 days",
    amount: 12000,
    remarks: "Non-conformity CAP under monitoring",
    stage: "Open",
    finalStatus: "In Progress",
    alertDays: 45,
    escalationL1: "QA Lead",
    escalationL2: "Operations Head",
    createdAt: "2024-11-10",
    updatedAt: "2025-01-05",
  },
  {
    id: "LN-006",
    department: "ENVIRONMENTAL",
    subject: "Environmental Compliance - Waste Management",
    inwardNumber: "IN-LN-2024-006",
    inwardDate: "2024-08-15",
    replies: [
      {
        text: "Waste audit completed successfully.",
        type: "Own",
        responsiblePerson: "Sustainability Officer",
        createdAt: "2024-09-01",
      },
      {
        text: "All requirements met. Approved by authority.",
        type: "Authority",
        responsiblePerson: "Environmental Department",
        createdAt: "2024-10-30",
      },
    ],
    period: "60 days",
    amount: 4200,
    remarks: "Quarterly waste management certification",
    stage: "Closed",
    finalStatus: "Resolved",
    alertDays: 0,
    escalationL1: "Operations Head",
    escalationL2: "CEO",
    createdAt: "2024-08-15",
    updatedAt: "2024-11-05",
  },
]

export function getDashboardMetrics() {
  const now = new Date()
  const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000)

  const expiringDocumentsCount = mockDocuments.filter((doc) => {
    const expiry = new Date(doc.expiryDate)
    return expiry <= thirtyDaysFromNow && expiry > now && doc.status !== "Expired"
  }).length

  const openLegalNoticesCount = mockLegalNotices.filter((n) => n.stage === "Open").length

  const highRiskCount =
    mockDocuments.filter((d) => d.status === "Expired").length +
    mockLegalNotices.filter((n) => n.stage === "Open" && n.period === "60 days").length

  return {
    expiringDocumentsCount,
    openLegalNoticesCount,
    highRiskCount,
  }
}
